/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStrategyRouteImport } from './routes/_app.strategy'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppLoansIndexRouteImport } from './routes/_app.loans.index'
import { Route as AppLoansAddRouteImport } from './routes/_app.loans.add'
import { Route as AppLoansLoanIdRouteImport } from './routes/_app.loans.$loanId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStrategyRoute = AppStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansIndexRoute = AppLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansAddRoute = AppLoansAddRouteImport.update({
  id: '/loans/add',
  path: '/loans/add',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansLoanIdRoute = AppLoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/strategy': typeof AppStrategyRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/loans/add': typeof AppLoansAddRoute
  '/loans/': typeof AppLoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/strategy': typeof AppStrategyRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/loans/add': typeof AppLoansAddRoute
  '/loans': typeof AppLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/strategy': typeof AppStrategyRoute
  '/_app/loans/$loanId': typeof AppLoansLoanIdRoute
  '/_app/loans/add': typeof AppLoansAddRoute
  '/_app/loans/': typeof AppLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/strategy'
    | '/loans/$loanId'
    | '/loans/add'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/strategy'
    | '/loans/$loanId'
    | '/loans/add'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/strategy'
    | '/_app/loans/$loanId'
    | '/_app/loans/add'
    | '/_app/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/strategy': {
      id: '/_app/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof AppStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/': {
      id: '/_app/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AppLoansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/add': {
      id: '/_app/loans/add'
      path: '/loans/add'
      fullPath: '/loans/add'
      preLoaderRoute: typeof AppLoansAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/$loanId': {
      id: '/_app/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AppLoansLoanIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStrategyRoute: typeof AppStrategyRoute
  AppLoansLoanIdRoute: typeof AppLoansLoanIdRoute
  AppLoansAddRoute: typeof AppLoansAddRoute
  AppLoansIndexRoute: typeof AppLoansIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStrategyRoute: AppStrategyRoute,
  AppLoansLoanIdRoute: AppLoansLoanIdRoute,
  AppLoansAddRoute: AppLoansAddRoute,
  AppLoansIndexRoute: AppLoansIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
